# Generated by Django 2.2.6 on 2019-10-21 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=70, verbose_name='Nome')),
                ('carga_horaria', models.IntegerField(verbose_name='Carga Horária')),
                ('ementa', models.CharField(max_length=100, verbose_name='Ementa')),
                ('valor', models.IntegerField(max_length=10, verbose_name='Valor')),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField(max_length=10, verbose_name='Data de Incio')),
                ('data_termino', models.DateField(max_length=10, verbose_name='Data do Termino')),
                ('hora_inicio', models.DateTimeField(max_length=5, verbose_name='Hora de Inicio')),
                ('hora_termino', models.DateTimeField(max_length=5, verbose_name='Hora do Termino')),
                ('Curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.Curso')),
            ],
        ),
    ]
