# Generated by Django 2.2.6 on 2019-10-21 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='hora_inicio',
            field=models.TimeField(max_length=5, verbose_name='Hora de Inicio'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='hora_termino',
            field=models.TimeField(max_length=5, verbose_name='Hora do Termino'),
        ),
    ]
