# Generated by Django 2.2.6 on 2019-10-21 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_auto_20191021_1552'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('telefone', models.CharField(max_length=13, verbose_name='Telefone')),
                ('valor_hora_aula', models.PositiveIntegerField(max_length=10)),
                ('Turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.Turma')),
            ],
        ),
    ]
