# Generated by Django 2.2.6 on 2019-10-24 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0003_professor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curso',
            options={'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
        migrations.AlterField(
            model_name='curso',
            name='carga_horaria',
            field=models.IntegerField(max_length=20, verbose_name='Carga Horária'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='data_inicio',
            field=models.DateField(verbose_name='Data de Incio'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='data_termino',
            field=models.DateField(verbose_name='Data do Termino'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='hora_inicio',
            field=models.TimeField(verbose_name='Hora de Inicio'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='hora_termino',
            field=models.TimeField(verbose_name='Hora do Termino'),
        ),
    ]
