# Generated by Django 2.2.6 on 2019-10-24 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0004_auto_20191024_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='carga_horaria',
            field=models.CharField(max_length=10, verbose_name='Carga Horária'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='valor',
            field=models.CharField(max_length=10, verbose_name='Valor'),
        ),
    ]
