# Generated by Django 2.2.6 on 2019-10-24 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0005_auto_20191024_1433'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='professor',
            options={'verbose_name_plural': 'Professores'},
        ),
        migrations.AlterModelOptions(
            name='turma',
            options={'verbose_name_plural': 'Turmas'},
        ),
        migrations.AddIndex(
            model_name='professor',
            index=models.Index(fields=['nome', 'telefone', 'valor_hora_aula'], name='cursos_prof_nome_aa6cd7_idx'),
        ),
        migrations.AddIndex(
            model_name='turma',
            index=models.Index(fields=['data_inicio', 'data_termino', 'hora_inicio', 'hora_termino'], name='cursos_turm_data_in_5ca60c_idx'),
        ),
    ]
