# Generated by Django 2.2.6 on 2019-10-24 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0006_auto_20191024_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='valor_hora_aula',
            field=models.CharField(max_length=10, verbose_name='Valor da Hora Aula'),
        ),
    ]
